"""Backend-neutral order, position, settlement, and ledger domain model."""

from weatherbot.domain.errors import (
    AggregateNotFound,
    DomainError,
    DuplicateEventConflict,
    InvalidTransition,
    InvariantViolation,
)
from weatherbot.domain.events import (
    AccountOpened,
    FillReceived,
    LedgerEvent,
    MarketResolutionEvidenceRecorded,
    MarketResolved,
    OrderAcknowledged,
    OrderCancelled,
    OrderIntentCreated,
    OrderOutcomeUnknown,
    OrderRejected,
    OrderSubmitted,
    PositionSettled,
    fingerprint,
)
from weatherbot.domain.model import (
    EventId,
    FillId,
    MarketId,
    MarketResolution,
    OrderAggregate,
    OrderIntent,
    OrderIntentId,
    OrderState,
    OutcomeId,
    OutcomePayout,
    Position,
    PositionStatus,
    PreTradeDecision,
    RiskDecisionStatus,
    Side,
    Signal,
    allowed_transitions,
    build_order_intent_id,
)
from weatherbot.domain.money import Money, as_decimal, money_from_unit_price
from weatherbot.domain.ports import ExecutionAdapter
from weatherbot.domain.reducers import apply_event, replay
from weatherbot.domain.resolution import (
    MarketResolutionEvidence,
    ResolutionEvidenceStatus,
)
from weatherbot.domain.state import LedgerState, PositionKey, position_key

__all__ = [
    "AccountOpened",
    "AggregateNotFound",
    "DomainError",
    "DuplicateEventConflict",
    "EventId",
    "ExecutionAdapter",
    "FillId",
    "FillReceived",
    "InvalidTransition",
    "InvariantViolation",
    "LedgerEvent",
    "LedgerState",
    "MarketId",
    "MarketResolution",
    "MarketResolutionEvidence",
    "MarketResolutionEvidenceRecorded",
    "MarketResolved",
    "Money",
    "OrderAcknowledged",
    "OrderAggregate",
    "OrderCancelled",
    "OrderIntent",
    "OrderIntentCreated",
    "OrderIntentId",
    "OrderOutcomeUnknown",
    "OrderRejected",
    "OrderState",
    "OrderSubmitted",
    "OutcomeId",
    "OutcomePayout",
    "Position",
    "PositionKey",
    "PositionSettled",
    "PositionStatus",
    "PreTradeDecision",
    "ResolutionEvidenceStatus",
    "RiskDecisionStatus",
    "Side",
    "Signal",
    "allowed_transitions",
    "apply_event",
    "as_decimal",
    "build_order_intent_id",
    "fingerprint",
    "money_from_unit_price",
    "position_key",
    "replay",
]
